#!/usr/bin/env bash
# ============================================================================
# sync-tokens.sh
# M3 卓越线补齐：Figma Tokens Studio → Style Dictionary → ColorTokens.kt 同步
# 流程：
#   1. 设计师在 Figma 用 Tokens Studio 插件定义 token，导出 design/tokens.json
#   2. 本脚本调 Style Dictionary 生成 ColorTokens.kt / SpacingTokens.kt 等
#   3. 生成的 .kt 文件覆盖 foundation/tokens/ 下对应文件
#   4. PR 包含 .kt diff，reviewer 视觉确认 + 截图测试验证
#
# 用法：
#   ./scripts/sync-tokens.sh                  # 全量生成
#   ./scripts/sync-tokens.sh --check          # 仅校验，不写文件（CI 用）
#   ./scripts/sync-tokens.sh --dry-run        # 预览生成内容，不写文件
# ============================================================================

set -euo pipefail

# 颜色
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# 路径
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TOKENS_JSON="$PROJECT_ROOT/design/tokens.json"
TEMPLATE_DIR="$PROJECT_ROOT/design/templates"
OUTPUT_DIR="$PROJECT_ROOT/app/src/main/java/com/pai/app/core/designsystem/foundation/tokens"
TEMP_DIR=$(mktemp -d)

trap "rm -rf $TEMP_DIR" EXIT

# 参数解析
DRY_RUN=false
CHECK_ONLY=false
for arg in "$@"; do
    case $arg in
        --dry-run)  DRY_RUN=true ;;
        --check)    CHECK_ONLY=true ;;
        -h|--help)
            echo "Usage: sync-tokens.sh [--check] [--dry-run]"
            echo "  --check     仅校验 tokens.json 是否需要重新生成（CI 用）"
            echo "  --dry-run   预览生成内容，不写文件"
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown argument: $arg${NC}"
            exit 1
            ;;
    esac
done

echo -e "${BLUE}=== Figma Tokens Sync ===${NC}"

# 1. 检查 tokens.json
if [ ! -f "$TOKENS_JSON" ]; then
    echo -e "${YELLOW}⚠ design/tokens.json 不存在${NC}"
    echo -e "  请设计师在 Figma 用 Tokens Studio 插件导出后放置到 design/tokens.json"
    echo -e "  当前使用手写的 ColorTokens.kt，跳过同步"
    exit 0
fi

echo -e "${GREEN}✓ 找到 tokens.json: $TOKENS_JSON${NC}"

# 2. 检查 Style Dictionary 是否安装
if ! command -v style-dictionary &> /dev/null; then
    echo -e "${YELLOW}⚠ Style Dictionary 未安装${NC}"
    echo -e "  请执行: npm install -g style-dictionary"
    echo -e "  或在项目根目录执行: npm install style-dictionary"
    exit 1
fi

# 3. 检查模板文件
if [ ! -d "$TEMPLATE_DIR" ]; then
    echo -e "${YELLOW}⚠ design/templates/ 不存在，创建默认模板${NC}"
    mkdir -p "$TEMPLATE_DIR"
    cat > "$TEMPLATE_DIR/ColorTokens.kt.template" <<'EOF'
// ============================================================================
// ColorTokens.kt
// AUTO-GENERATED by sync-tokens.sh from design/tokens.json
// DO NOT EDIT MANUALLY — change Figma Tokens Studio and re-run sync
// ============================================================================
package com.pai.app.core.designsystem.foundation.tokens

import androidx.compose.ui.graphics.Color

{{#tokens}}
val {{name}} = Color({{value}})
{{/tokens}}
EOF
fi

# 4. 配置 Style Dictionary
cat > "$TEMP_DIR/config.json" <<EOF
{
  "source": ["$TOKENS_JSON"],
  "platforms": {
    "kotlin": {
      "transformGroup": "compose",
      "buildPath": "$TEMP_DIR/",
      "files": [{
        "destination": "ColorTokens.kt",
        "template": "kotlin/color"
      }]
    }
  }
}
EOF

# 5. 运行 Style Dictionary
echo -e "${BLUE}生成 Kotlin Token 文件...${NC}"
if [ "$DRY_RUN" = true ]; then
    echo -e "${YELLOW}[DRY-RUN] 跳过实际生成${NC}"
    exit 0
fi

style-dictionary build --config "$TEMP_DIR/config.json" --template-dir "$TEMPLATE_DIR" || {
    echo -e "${RED}✗ Style Dictionary 生成失败${NC}"
    echo -e "  请检查 tokens.json 格式是否符合 Tokens Studio 规范"
    exit 1
}

# 6. 检查是否有 diff
if [ "$CHECK_ONLY" = true ]; then
    if diff -q "$TEMP_DIR/ColorTokens.kt" "$OUTPUT_DIR/ColorTokens.kt" &> /dev/null; then
        echo -e "${GREEN}✓ ColorTokens.kt 已是最新${NC}"
        exit 0
    else
        echo -e "${RED}✗ ColorTokens.kt 与 tokens.json 不一致${NC}"
        echo -e "  请执行 ./scripts/sync-tokens.sh 重新生成并提交"
        exit 1
    fi
fi

# 7. 应用变更
cp "$TEMP_DIR/ColorTokens.kt" "$OUTPUT_DIR/ColorTokens.kt"
echo -e "${GREEN}✓ 已更新 $OUTPUT_DIR/ColorTokens.kt${NC}"

# 8. 提示后续动作
echo ""
echo -e "${BLUE}=== 同步完成 ===${NC}"
echo -e "下一步建议："
echo -e "  1. ${YELLOW}git diff${NC} 查看 ColorTokens.kt 变更"
echo -e "  4. 提交 PR 包含 tokens.json + .kt diff + 截图 diff"
